allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  puppeteer: false
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - sharp
  - unrs-resolver
